import { Product } from './product.type';

export const PRODUCTS: Product[] = [
  {
    id: 0,
    name: 'Doliprane',
    brand: 'Sanofi',
    category: 'Antalgique',
    price: 4.99,
    new: false,
    hot: true,
    image: '../assets/images/products/doliprane.png',
  },
  {
    id: 1,
    name: 'Efferalgan',
    brand: 'Bristol-Myers Squibb',
    category: 'Antalgique',
    price: 5.99,
    new: false,
    hot: true,
    image: '../assets/images/products/efferalgan.png',
  },
  {
    id: 2,
    name: 'Fervex',
    brand: 'UPSAt',
    category: 'Fièvre et Rhume',
    price: 7.49,
    new: true,
    hot: false,
    image: '../assets/images/products/fervex.png',
  },
  {
    id: 3,
    name: 'Nurofen',
    brand: 'Reckitt Benckiser',
    category: 'Anti-inflammatoire',
    price: 8.99,
    new: false,
    hot: false,
    image: '../assets/images/products/Nurofen.png',
  },
  {
    id: 4,
    name: 'Humex',
    brand: 'URGO',
    category: 'Toux',
    price: 6.99,
    new: false,
    hot: true,
    image: '../assets/images/products/Humex.png',
  },
  {
    id: 5,
    name: 'Vicks Vaporub',
    brand: 'Procter & Gamble',
    category: 'Inhalation',
    price: 9.99,
    new: true,
    hot: true,
    image: '../assets/images/products/Vicks-Vaporub.png',
  },
  {
    id: 6,
    name: 'Bi-Oil',
    brand: 'Laboratoire Genevrier',
    category: 'Soin de la peau',
    price: 12.99,
    new: true,
    hot: false,
    image: '../assets/images/products/Bi-Oil.jpg',
  },
  {
    id: 7,
    name: 'Smecta',
    brand: 'Ipsen',
    category: 'Troubles digestifs',
    price: 5.99,
    new: true,
    hot: true,
    image: '../assets/images/products/Smecta.png',
  },
  {
    id: 8,
    name: 'Oscillococcinum',
    brand: 'Boiron',
    category: 'Homéopathie',
    price: 15.99,
    new: true,
    hot: false,
    image: '../assets/images/products/Oscillococcinum.jpeg',
  },
  {
    id: 9,
    name: 'Physiomer',
    brand: 'Laboratoire de la Mer',
    category: 'Rhinologie',
    price: 8.99,
    new: true,
    hot: false,
    image: '../assets/images/products/Physiomer.webp',
  },
  {
    id: 10,
    name: 'Lactibiane',
    brand: 'Pileje',
    category: 'Probiotiques',
    price: 9.99,
    new: true,
    hot: false,
    image: '../assets/images/products/Lactibiane.jpg',
  },
  {
    id: 11,
    name: 'Arnigel',
    brand: 'Boiron',
    category: 'Traumatologie',
    price: 7.99,
    new: false,
    hot: true,
    image: '../assets/images/products/Arnigel.avif',
  },
  {
    id: 12,
    name: 'Cicabio Crème',
    brand: 'Bioderma',
    category: 'Cicatrisation',
    price: 10.99,
    new: false,
    hot: true,
    image: '../assets/images/products/Cicabio-Crème.png',
  },
  {
    id: 13,
    name: 'Exomega Baume Émollient',
    brand: 'A-Derma',
    category: 'Peau atopique',
    price: 15.99,
    new: false,
    hot: false,
    image: '../assets/images/products/Exomega-Baume.jpg',
  },
  {
    id: 14,
    name: 'SoluStrept',
    brand: 'Bayer',
    category: 'Antibiotique',
    price: 12.99,
    new: false,
    hot: false,
    image: '../assets/images/products/doliprane.png',
  },
  {
    id: 15,
    name: 'Euphytose',
    brand: 'Mayoly-Spindler',
    category: 'Troubles du sommeil',
    price: 8.99,
    new: true,
    hot: false,
    image: '../assets/images/products/Euphytose.avif',
  },

  {
    id: 16,
    name: 'Dafalgan',
    brand: 'Johnson & Johnson',
    category: 'Antalgique',
    price: 3.99,
    new: false,
    hot: true,
    image: '../assets/images/products/Dafalgan.webp',
  },
];
